apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: elastic-stack
spec:
  count: 1
  elasticsearchRefs:
    - name: elasticsearch
      clusterName: qs
  version:  9.1.0
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "https://elasticsearch-es-http:9200" ]
            user => "elastic"
            password => "ES_PASSWORD"
            ssl_verification_mode => "none"
            index => "%{[kubernetes][container][name]}-%{+YYYY.MM.dd}"
          }
        }
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044